# DEV environment

app:
  message: "This application is running on DEV environment"

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projetospringboot
    username: postgres
    password: postgres

security:
  config:
    prefix: Bearer
    key: uTWtO(0y<[K9hlQ$eOtM=e2lL3b|XR%pg."S4n40k:wz$(%c64:vo_O&%$}Dd9;
    expiration: 3600000